services:
  # Database Service
  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass
    volumes:
      - mysql_data:/var/lib/mysql

  # Gorse Service (All-in-one node)
  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - "8087:8087" # gRPC port
      - "8088:8088" # HTTP API and Dashboard port
    environment:
      # Use MySQL as cache storage backend
      GORSE_CACHE_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
      # Use MySQL as data storage backend
      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
    depends_on:
      - mysql
    volumes:
      - ./config.toml:/etc/gorse/config.toml
    command: -c /etc/gorse/config.toml

volumes:
  mysql_data: